# Generated by Django 5.0.1 on 2024-01-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_customer_product_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='customername',
        ),
    ]
