# Generated by Django 5.0.1 on 2024-01-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_name_customer_customername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customername',
            new_name='name',
        ),
    ]
