# Generated by Django 5.0.1 on 2024-01-23 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_purchasedproduct_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='purchasedproduct',
            name='product_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.product'),
            preserve_default=False,
        ),
    ]
