# Generated by Django 5.0.1 on 2024-01-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_remove_purchasedproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedproduct',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
    ]
