# Generated by Django 5.0.1 on 2024-01-23 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_purchasedproduct_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedproduct',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.product'),
        ),
    ]
